Name = input ("Enter Name: ")
print (Name)
Age = input ("Enter Age: ")
print (Age)
University = input ("Enter University: ")
print (University)
Address = input ("Enter Address: ")
print (Address)
Father = input ("Enter Fathers name: ")
print (Father)
Mother = input ("Enter Mothers name: ")
print (Mother)
ID = input ("Enter Student ID: ")
print (ID)
Guardian = input ("Enter Guardian name: ")
print (Guardian)
Bus = input ("Enter Bus number: ")
print (Bus)
Mobile = input ("Enter Mobile number: ")
print (Mobile)